In [3]:
import pandas as pd

df_charts = pd.read_csv("charts.csv")

df_charts.head()

,date,rank,song,artist,last-week,peak-rank,weeks-on-board
0,2021-11-06,1,Easy On Me,Adele,1.0,1,3
1,2021-11-06,2,Stay,The Kid LAROI & Justin Bieber,2.0,1,16
2,2021-11-06,3,Industry Baby,Lil Nas X & Jack Harlow,3.0,1,14
3,2021-11-06,4,Fancy Like,Walker Hayes,4.0,3,19
4,2021-11-06,5,Bad Habits,Ed Sheeran,5.0,2,18

In [4]:
df_charts['date'] = pd.to_datetime(df_charts['date'])

df_2010 = df_charts[
    (df_charts['date'].dt.year == 2010) &
    (df_charts['rank'] <= 10)
]

print("Total Top 10 entries in 2010:", len(df_2010))

Total Top 10 entries in 2010: 520

In [ ]:
sample_songs = df_2010.sample(20, random_state=42)

sample_songs[['song', 'artist']]

                       song                           artist
59401                   OMG        Usher Featuring will.i.am
59709      Hey, Soul Sister                            Train
60801               BedRock      Young Money Featuring Lloyd
61702           Bad Romance                        Lady Gaga
58805        Cooler Than Me                      Mike Posner
61804             Fireflies                         Owl City
61309      Hey, Soul Sister                            Train
60309               BedRock      Young Money Featuring Lloyd
59506        Nothin' On You       B.o.B Featuring Bruno Mars
60608             Telephone      Lady Gaga Featuring Beyonce
57900  Just The Way You Are                       Bruno Mars
57705              Dynamite                        Taio Cruz
59103             Airplanes  B.o.B Featuring Hayley Williams
61003               BedRock      Young Money Featuring Lloyd
59001  Love The Way You Lie         Eminem Featuring Rihanna
60506      Hey, Soul Sister                            Train
57106       What's My Name?          Rihanna Featuring Drake
61603  Empire State Of Mind              Jay-Z + Alicia Keys
57608  Club Can't Handle Me  Flo Rida Featuring David Guetta
60705               TiK ToK                            Ke$ha

In [13]:
import requests
import time

def get_mbid(title, artist):
    query = f'recording:"{title}" AND artist:"{artist}"'
    url = "https://musicbrainz.org/ws/2/recording/"
    params = {
        "query": query,
        "fmt": "json"
    }
    
    r = requests.get(url, params=params)
    if r.status_code != 200:
        return None
    
    data = r.json()
    
    if data.get("recordings"):
        return data["recordings"][0]["id"]
    
    return None

def check_acousticbrainz(mbid):
    url = f"https://acousticbrainz.org/{mbid}/low-level"
    r = requests.get(url)
    return r.status_code == 200

In [14]:
found = 0
total = len(sample_songs)

for _, row in sample_songs.iterrows():
    title = row['song']   # adjust if needed
    artist = row['artist']
    
    mbid = get_mbid(title, artist)
    
    if mbid and check_acousticbrainz(mbid):
        found += 1
    
    time.sleep(1)

print("Found:", found)
print("Coverage %:", found / total * 100)

Found: 6
Coverage %: 30.0